### ISSUE TITLE
All ok local but nothing happens in production

### ISSUE THREAD

**Issue by 4n70w4** [ansible-collections/community.postgresql#111]
##### SUMMARY

I run `community.postgresql.postgresql_user` in production but after 10 min of waiting nothing happens.

![image](https://user-images.githubusercontent.com/38257723/124812943-ef594880-df6c-11eb-85b4-416272dc5df2.png)

![image](https://user-images.githubusercontent.com/38257723/124811232-e8c9d180-df6a-11eb-9621-ba490adfd566.png)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.postgresql.postgresql_user

##### ANSIBLE VERSION

```paste below
ansible 2.9.12
  config file = /home/xxxxx/ansible/ansible.cfg
  configured module search path = ['/usr/local/lib/python3.8/dist-packages/git_acp/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
```

##### COLLECTION VERSION

```paste below
usage: ansible-galaxy collection [-h] COLLECTION_ACTION ...
ansible-galaxy collection: error: argument COLLECTION_ACTION: invalid choice: 'list' (choose from 'init', 'build', 'publish', 'install')
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/home/xxx/ansible/ansible.cfg) = True
DEFAULT_HOST_LIST(/home/xxx/ansible/ansible.cfg) = ['/home/xxx/ansible/hosts.ini']
DEFAULT_LOG_PATH(/home/xxx/ansible/ansible.cfg) = /home/xxx/ansible/ansible.log
DEFAULT_MODULE_PATH(/home/xxx/ansible/ansible.cfg) = ['/usr/local/lib/python3.8/dist-packages/git_acp/modules']
DEFAULT_VAULT_PASSWORD_FILE(/home/xxx/ansible/ansible.cfg) = /home/xxx/.ansible_pass.txt
HOST_KEY_CHECKING(/home/xxx/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/home/xxx/ansible/ansible.cfg) = /usr/bin/python3.8
```

##### OS / ENVIRONMENT

Local (all ok)

```
lsb_release -a
```

```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```

Prod (nothing happens)

```
lsb_release -a
```

```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

```

##### STEPS TO REPRODUCE

```yaml
  - name: Create jirauser user, and grant access to database jira
    community.postgresql.postgresql_user:
      state: present
      login_host: localhost
      login_user: postgresql
      login_password: "{{ postgresql_root_password }}"
      name: jirauser
      password: {{ p }}
      expires: infinity
```

##### EXPECTED RESULTS

All ok.

```
TASK [Create jirauser user, and grant access to database jira] **********************************************************************
task path: /home/xxx/ansible/roles/jira/tasks/main.yml:24
Using module file /root/.ansible/collections/ansible_collections/community/postgresql/plugins/modules/postgresql_user.py
Pipelining is enabled.
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 && sleep 0'
[WARNING]: The value ******** (type int) in a string field was converted to '********' (type string). If this does not look like
what you expect, quote the entire value to ensure it does not change.
ok: [xxx] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ca_cert": null,
            "comment": null,
            "conn_limit": null,
            "db": "",
            "encrypted": true,
            "expires": "infinity",
            "fail_on_user": true,
            "groups": null,
            "login_host": "localhost",
            "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "login_unix_socket": "",
            "login_user": "postgres",
            "name": "jirauser",
            "no_password_changes": false,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 5432,
            "priv": null,
            "role_attr_flags": "",
            "session_role": null,
            "ssl_mode": "prefer",
            "state": "present",
            "trust_input": true,
            "user": "jirauser"
        }
    },
    "queries": [],
    "user": "jirauser"
}
```

##### ACTUAL RESULTS

Nothing happens.

```paste below
TASK [Create jirauser user, and grant access to database jira] **********************************************************************
task path: /home/xxx/ansible/roles/jira/tasks/main.yml:24
Using module file /root/.ansible/collections/ansible_collections/community/postgresql/plugins/modules/postgresql_user.py
Pipelining is enabled.
<xxx> ESTABLISH SSH CONNECTION FOR USER: None
<xxx> SSH: EXEC sshpass -d12 ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/4b2924865d xxx '/bin/sh -c '"'"'/usr/bin/python3 && sleep 0'"'"''
```

**Comment by Andersson007** [comment]
@4n70w4 hi, thanks for reporting the issue. How about other modules (not from `community.postgresql`)? Did you try the `setup` module for example? At first glance, this looks like something connection related, like a firewall issue.

**Comment by 4n70w4** [comment]
I don't have firewall. At least I haven't installed or configured it.  May be only something by default. 
`community.mysql.mysql_user` works ok.

**Comment by Andersson007** [comment]
@4n70w4 thanks for the feedback. Could you please try also `postgresql_info` module?

**Comment by 4n70w4** [comment]
`postgresql_info` also works local and infinite waiting on prod.

Probably there really is a problem with the connection to the postres. I would like the module to report this instead infinite waiting. 

local:
![image](https://user-images.githubusercontent.com/38257723/124889593-eb1a4300-dfdf-11eb-8f11-5ef33481331e.png)

![image](https://user-images.githubusercontent.com/38257723/124889800-19981e00-dfe0-11eb-9a61-196d8806b190.png)

prod:

![image](https://user-images.githubusercontent.com/38257723/124889942-3a607380-dfe0-11eb-9cd6-173443432320.png)

![image](https://user-images.githubusercontent.com/38257723/124890034-4e0bda00-dfe0-11eb-8aef-c97f1f404be2.png)

Very strange, locally and in production, postgres is deployed through one role.

I will debug it. Thanks for the support.

**Comment by Andersson007** [comment]
@4n70w4 thanks for checking. Please let us know results of your investigation (even if you don't find the root of the problem). Thank you

**Comment by Andersson007** [comment]
(also if you know python and find a solution when investigating (maybe there's a timeout option for the DB driver or something, we have a quick start guide [here](https://github.com/ansible/community-docs/blob/main/create_pr_quick_start_guide.rst))

**Comment by 4n70w4** [comment]
All easy! Need use `127.0.0.1` instead `localhost`. `localhost` resolved to `::1` instead `127.0.0.1`.
I don’t know why, I didn’t configure it. Perhaps it was configured by the provider. Or the side effect of something. 

````
PGPASSWORD=***** psql -U postgres -p 5432 -h 127.0.0.1
````

```
psql (10.17 (Ubuntu 10.17-0ubuntu0.18.04.1), server 11.8 (Debian 11.8-1.pgdg90+1))
WARNING: psql major version 10, server major version 11.
         Some psql features might not work.
Type "help" for help.

postgres=#
```


```
ping 127.0.0.1
```

```
PING 127.0.0.1 (127.0.0.1) 56(84) bytes of data.
64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.072 ms
64 bytes from 127.0.0.1: icmp_seq=2 ttl=64 time=0.053 ms

--- 127.0.0.1 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1030ms
rtt min/avg/max/mdev = 0.053/0.062/0.072/0.012 ms
```

```
PGPASSWORD=***** psql -U postgres -p 5432 -h localhost
````

```
ping localhost
```

```
PING localhost(localhost (::1)) 56 data bytes
64 bytes from localhost (::1): icmp_seq=1 ttl=64 time=0.038 ms
64 bytes from localhost (::1): icmp_seq=2 ttl=64 time=0.045 ms
64 bytes from localhost (::1): icmp_seq=3 ttl=64 time=0.049 ms

--- localhost ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2033ms
rtt min/avg/max/mdev = 0.038/0.044/0.049/0.004 ms

```

I run postgrs in docker swarm with port forwarding and connect to them from host.

```
version: '3.8'

networks:
    traefik:
        external: true


services:

  postgresql:
    image: postgres:11.8
    ports:
      - target: 5432
        published: 5432
        mode: ingress
    volumes:
     - {{ postgresql_data_directory }}:/var/lib/postgresql/data
#     - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
     - traefik
    environment:
      POSTGRES_PASSWORD: {{ postgresql_root_password }}
```


But that's not all! 

If I replace `mode: ingress` to `mode: host` then I can connect to postgres via `localhost`, but `localhost` still resolved as  `::1`.
For me, this is magic!

But all combinations of `mode: ingress` / ` mode: host` and `localhost` / `127.0.0.1` works on the local machine.

**Comment by Andersson007** [comment]
Cool, thanks for the feedback!
Would be nice to add a note to the documentation of the `login_host` option, something like "- If you have connection issues when using C(localhost), try to use C(127.0.0.1) instead." or something else short but informative.
I think it would make users life easier.
Would you like to raise a PR for that?
I think it's possible to change the `plugins/doc_fragments/postgres.py` file via GH interface ("Edit" button) and create the PR.

**Comment by Andersson007** [comment]
@4n70w4 thanks for reporting this! I added the note to the doc, I hope it will help.
