### ISSUE TITLE
Release plan

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/community.postgresql#13]
##### SUMMARY
_(partially copied from https://github.com/ansible-collections/community.crypto/issues/74 , thanks to @felixfontein)_

We should decide on how to release this collection (w.r.t. versioning).
Small collections like this one don't need a complex plan like the one for community.general and community.network.
So how about the following?

1. Release minor and patch releases whenever we want (like after adding new features or fixing bugs). Since this collection is small, there's no need to fix things in advance. Just add features, and after a feature either wait a bit longer for more features/bugs, or make a release.

I suggest releasing without branching https://github.com/ansible/community-docs/blob/main/releasing_collections_without_release_branches.rst
Breaking changes don't work with this schema but we might change the approach and start releasing from branches when needed.

For release support timeline, refer to [README](https://github.com/ansible-collections/community.postgresql/blob/main/README.md) (we should keep it updated)

First release will be 0.1.0

**Comment by Andersson007** [comment]
cc @Andersson007 @Dorn- @andytom @antoinell @archf @b6d @dschep @ilicmilan @jbscalia @jensdepuydt @kostiantyn-nemchenko @matburt @nerzhul @sebasmannem @strk @tcraxs @wrouesnel

**Comment by Andersson007** [comment]
`community.postgresql` 0.1.0 has just been released

**Comment by Andersson007** [comment]
FYI: I will likely release `community.postgresql` 1.0.0 tomorrow 17.11.2020. If anybody has something urgent to review and merge, please let me know

**Comment by Andersson007** [comment]
1.0.0 has just been released!

**Comment by Andersson007** [comment]
I'm going to release version 1.1.0 on Monday January 18 (if time allows)

**Comment by Andersson007** [comment]
`community.postgresql` 1.1.0 has been released

**Comment by Andersson007** [comment]
`community.postgresql` 1.1.1 has been released

**Comment by Andersson007** [comment]
`community.postgresql` 1.2.0 has been released

**Comment by Andersson007** [comment]
I'm gonna release c.postgresql 1.3.0 now

**Comment by Andersson007** [comment]
community.postgresql 1.3.0 has been released

**Comment by Andersson007** [comment]
I'm gonna release c.postgresql 1.4.0 now

**Comment by Andersson007** [comment]
`community.postgresql` 1.4.0 has been released

**Comment by Andersson007** [comment]
i'm gonna release `community.postgresql` 1.5.0 today

**Comment by Andersson007** [comment]
`community.postgresql` 1.5.0 has been release (great release, folks!)

**Comment by Andersson007** [comment]
I'm gonna release c.postgresql 1.6.0 now

**Comment by Andersson007** [comment]
`community.postgresql` 1.6.0 has been release. Contains doc fixes and https://github.com/ansible-collections/community.postgresql/pull/163.

**Comment by Andersson007** [comment]
@marcosdiez after https://github.com/ansible-collections/community.postgresql/pull/173 is slightly corrected and integration tests added, we could merge it and release `1.6.1`.

**Comment by Andersson007** [comment]
`community.postgresql` 1.6.1 has been released.

**Comment by Andersson007** [comment]
@tcraxs @marcosdiez @hunleyd @MichaelDBA ^ is available for installation via `ansible-galaxy` right now and will be included in the next Ansible package release. It contains the fixes for `postgresql_info` including the AWS-related (thanks to @marcosdiez).

Also not having an explicit code approval for https://github.com/ansible-collections/community.postgresql/pull/177, we can't proceed with the `conn_error_msg` feature for `postgresql_ping` module (yeah, the feature is approved by the vast majority but still not the code itself). So, just a fyi, still waiting for the code review.

**Comment by Andersson007** [comment]
`community.postgresql` [1.7.0](https://github.com/ansible-collections/community.postgresql/blob/stable-1/CHANGELOG.rst) and [2.0.0](https://github.com/ansible-collections/community.postgresql/blob/main/CHANGELOG.rst) have been released. Many thanks to [hunleyd](https://github.com/hunleyd), [klando](https://github.com/klando), [MichaelDBA](https://github.com/MichaelDBA), [marcosdiez](https://github.com/marcosdiez), [tcrax](https://github.com/tcraxs), [felixfontein](https://github.com/felixfontein), and [jtelcontar](https://github.com/jtelcontar)!

**Comment by Andersson007** [comment]
I'm going to release `community.postgresql` 2.1.0 today.

**Comment by Andersson007** [comment]
`community.postgresql` [2.1.0](https://github.com/ansible-collections/community.postgresql/blob/main/CHANGELOG.rst) has been released.

**Comment by Andersson007** [comment]
I'm going to release `community.postgresql` 1.7.1 today

**Comment by hunleyd** [comment]
`community.postgresql` [1.7.1](https://github.com/ansible-collections/community.postgresql/releases/tag/1.7.1) and [2.1.1](https://github.com/ansible-collections/community.postgresql/releases/tag/2.1.1) has been released. Many thanks to [Andersson007](https://github.com/Andersson007), [amossc](https://github.com/amossc), and [telcontar](https://github.com/jtelcontar)!

**Comment by Andersson007** [comment]
The [milestone](https://github.com/ansible-collections/community.postgresql/milestone/1) for next major release 3.0.0 has been created.
Thanks @hunleyd for doing this!
fyi: I added all related issues and PRs.

**Comment by hunleyd** [comment]
i plan on releasing 2.1.2 today

**Comment by hunleyd** [comment]
`community.postgresql` [2.1.2](https://github.com/ansible-collections/community.postgresql/releases/tag/2.1.2) has been released. Many thanks to @Andersson007

**Comment by hunleyd** [comment]
i plan on releasing `community.postgresql` 1.7.2 and 2.1.3 today.

**Comment by Andersson007** [comment]
@hunleyd thanks for releasing!

**Comment by hunleyd** [comment]
i plan on releasing community.postgresql 1.7.3 and 2.1.4 today.

**Comment by hunleyd** [comment]
`community.postgresql` [1.7.3](https://github.com/ansible-collections/community.postgresql/releases/tag/1.7.3) and [2.1.4](https://github.com/ansible-collections/community.postgresql/releases/tag/2.1.4) have been released. Thanks to our newest contributor @jchancojr and everyone else involved!

**Comment by Andersson007** [comment]
As ansible-core 2.14 is [scheduled](https://docs.ansible.com/ansible-core/devel/roadmap/ROADMAP_2_14.html) for release in November, I suggest releasing c.p. 3.0.0 in ~December (depending on an actual release date of ansible-core). [Release issue](https://github.com/ansible-collections/community.postgresql/issues/210).

**Comment by hunleyd** [comment]
i plan on releasing community.postgresql 1.7.4 and 2.1.5 today.

**Comment by hunleyd** [comment]
`community.postgresql` [1.7.4](https://github.com/ansible-collections/community.postgresql/releases/tag/1.7.4) and [2.1.5](https://github.com/ansible-collections/community.postgresql/releases/tag/2.1.5) have been released.

**Comment by Andersson007** [comment]
> There's an open question for @Andersson007 on #303 that I'm holding on. Once he's back from vacation and can advise, we'll cut a release shortly thereafter @betanummeric

Answered:) feel free to proceed with releasing (if no time, please let me know), thanks!

**Comment by Andersson007** [comment]
@betanummeric would you like to release the collection yourself? I'll provide all the guidelines needed if yes.

**Comment by betanummeric** [comment]
@Andersson007 Ok, let me try it. What do I need to do?

**Comment by Andersson007** [comment]
@betanummeric great, thanks! The process is actually pretty straightforward.

- I've just invited you with "write" access to the repo. Could you please accept it in a corresponding email you'll get? Can we consider you a maintainer after that? There will be nothing obligatory. One thing, do not merge your own PRs without at least one other maintainer's approval
- We release versions 1.* from `stable-1`. We backport only bugfixes to previous versions (NO new features / NO major changes), so we can see on the [tags](https://github.com/ansible-collections/community.postgresql/tags) page that the next 1.* release will be `1.7.5` as the latest one is 1.7.4 currently
- We release versions 2.* (the current latest major version) from `main`. Looking at the [changelog fragments](https://github.com/ansible-collections/community.postgresql/tree/main/changelogs/fragments) I can see that there are also minor changes, so, as we follow SemVer, we need to release the next minor release, i.e. `2.2.0` (you can also see `major_changes:` keys in the fragments but they only announce breaking changes that will happen in the next major release in half a year, so ignore them)
- Use the [releasing guidelines](https://docs.ansible.com/ansible/devel/community/collection_contributors/collection_release_without_branches.html) to release `1.7.5` and `2.2.0`
- First release `1.7.5` from `stable-1` (when the release PR is ready, please wait for our approval). The order is important as GitHub doesn't care about release numbers but only about an order. If you release 1.7.5 after 2.2.0, 1.7.5 will be shown as the latest release on the home repo page ad we don't want it:)
- Then release `2.2.0` from `main` (when the release PR is ready, please wait for our approval)

If any questions along the way, feel free to ask. @hunleyd or I should be here. Also you can join https://matrix.to/#/#postgresql:ansible.com on Matrix.

**Comment by betanummeric** [comment]
community.postgresql [1.7.5](https://github.com/ansible-collections/community.postgresql/releases/tag/1.7.5) and [2.2.0](https://github.com/ansible-collections/community.postgresql/releases/tag/2.2.0) have been released.

**Comment by hunleyd** [comment]
i plan on releasing 1.7.6 and 2.2.1 today

**Comment by hunleyd** [comment]
`community.postgresql` [1.7.6](https://github.com/ansible-collections/community.postgresql/releases/tag/1.7.6) and [2.3.0](https://github.com/ansible-collections/community.postgresql/releases/tag/2.3.0) have been released finally

**Comment by Andersson007** [comment]
i plan on releasing 2.3.1 today

**Comment by Andersson007** [comment]
The community.postgresql collection version 2.3.1 has been released ([changelog](https://github.com/ansible-collections/community.postgresql/blob/main/CHANGELOG.rst)). Thanks to @vonschultz and @hunleyd !

**Comment by betanummeric** [comment]
I'm going to release 2.3.2 and 1.7.7 today

**Comment by betanummeric** [comment]
`community.postgresql` [1.7.7](https://github.com/ansible-collections/community.postgresql/releases/tag/1.7.7) and [2.3.2](https://github.com/ansible-collections/community.postgresql/releases/tag/2.3.2) are released now

**Comment by betanummeric** [comment]
I plan to release 2.4.0 and 1.7.8 today

**Comment by betanummeric** [comment]
`community.postgresql` [1.7.8](https://github.com/ansible-collections/community.postgresql/releases/tag/1.7.8) and [2.4.0](https://github.com/ansible-collections/community.postgresql/releases/tag/2.4.0) are released now.

**Comment by betanummeric** [comment]
`community.postgresql` [1.7.9](https://github.com/ansible-collections/community.postgresql/releases/tag/1.7.9) and [2.4.1](https://github.com/ansible-collections/community.postgresql/releases/tag/2.4.1) have been released now. They revert the breaking change accidentally introduced in the previous version.

**Comment by Andersson007** [comment]
The [community.postgresql](https://galaxy.ansible.com/community/postgresql) collection versions [1.7.10](https://github.com/ansible-collections/community.postgresql/blob/stable-1/CHANGELOG.rst) and [2.4.2](https://github.com/ansible-collections/community.postgresql/blob/main/CHANGELOG.rst) collection have been released!

**Comment by Andersson007** [comment]
The [community.postgresql](https://galaxy.ansible.com/community/postgresql) collection versions versions [1.7.11](https://github.com/ansible-collections/community.postgresql/blob/stable-1/CHANGELOG.rst), [2.4.3](https://github.com/ansible-collections/community.postgresql/blob/stable-2/CHANGELOG.rst), and [3.1.0](https://github.com/ansible-collections/community.postgresql/blob/main/CHANGELOG.rst) were release by @aleksvagachev. Special thanks to @RealGreenDragon and @elpavel who rocked throughout the recent months and out maintainers team: @hunleyd @betanummeric @aleksvagachev @jchancojr for reviewing, merging and releasing stuff.

Also added a [note](https://matrix.to/#/!pMZboYFCScZJfXmOtH:ansible.im/$UMUiMjWLI4KqOzyJwqZHwN7ivwz9vLvcHKiGdEMI-BE?via=ansible.com&via=matrix.org&via=libera.chat) for Bullhorn.

**Comment by hunleyd** [comment]
as per a discussion with @Andersson007 releases will be announced in the forums instead of this issue going forward. as such, unpinning and closing.
