### ISSUE TITLE
Add TimeZone example in doc

### ISSUE THREAD

**Issue by marcflausino** [ansible-collections/community.postgresql#139]
##### SUMMARY
Hello,

I lost a few hours trying to understand why i got an error like '**No such parameter**' while setting '**timezone**' with **postgresql_set**.

Finally i ended up on this post : [https://github.com/ansible-collections/community.postgresql/issues/41](https://github.com/ansible-collections/community.postgresql/issues/41)

I'm sure, many will have the same troubleshoot with that parameter so i guess it would be nice to add an example on the documentation with that TimeZone name, and maybe add an explanation or a warning somehow.

What do you think ?

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
postgresql_set

##### ANSIBLE VERSION

```paste below
ansible 2.10.6
```

**Comment by Andersson007** [comment]
@marcflausino thanks for reporting the issue!

We could:
1) add something like `- Pay attention that parameters are case sensitive.` to the `name:` option.
2) an additional example to the EXAMPLES block

@marcflausino would you like to submit a quick PR? You can do it via GH web interface (find the file in `plugins/modules/postgresql_set.py` -> Edit) or via a classic method using this [tutorial](https://github.com/ansible/community-docs/blob/main/create_pr_quick_start_guide.rst) (feel free to skip all steps related to testing and changelog fragment). What do you think?

**Comment by Andersson007** [comment]
@marcflausino the DOCUMENTATION and EXAMPLES blocks in `plugins/modules/postgresql_set.py` is all that you need to improve.

**Comment by marcflausino** [comment]
hi @Andersson007 , ok i will make the PR

**Comment by Andersson007** [comment]
closed via https://github.com/ansible-collections/community.postgresql/pull/140
