### ISSUE TITLE
CI: integration testing against all supported Postgres versions

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/community.postgresql#154]
##### SUMMARY
- Currently we tests using AZP and several distros with default Postgres versions available for each distro. See `.azure-pipelines/azure-pipelines.yml` file.
- Postgres 14 has been recently released with some breaking changes and we don't have testing against it yet.

**Solution:**
- Moving to GitHub actions
- Testing using one distro against all supported Postgres versions + maybe 9.2
- An example is [community.mysql](https://github.com/ansible-collections/community.mysql) collection, `.github` directory content

**Temporary solution** (done with Added with https://github.com/ansible-collections/community.postgresql/pull/156) can be using one of the distros (say, Ubuntu 20.04 or whatever) to install Postgres 14.

**Comment by klando** [comment]
https://github.com/ansible-collections/community.postgresql/pull/166 is covering all PostgreSQL versions on ubuntu-2004

**Comment by Andersson007** [comment]
closing this to keep the tracker clean, thanks everyone!
