### ISSUE TITLE
Refactor module arguments: Remove `[NO]` prefix

### ISSUE THREAD

**Issue by gundalow** [ansible-collections/community.postgresql#161]
##### SUMMARY
Thanks to @Oloryn and @ssbarnea for reporting this issue and digging into the code.

We need to refactor the module arguments in some of the community.postgresql modules, rather than using the `[NO]SUPERUSER` shorthand as this:
1. isn't how we normally document Ansible module's parameters
2. breaks [vscode-ansible](https://github.com/ansible/vscode-ansible)'s parsing of module arguments.

This was reported in `postgresql_user` parameter `role_attr_flags`, though it likely applies to a few of the postgresql modules

For background please see https://github.com/ansible/vscode-ansible/issues/292

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
postgresql_user

**Comment by Andersson007** [comment]
Looking, thanks for reporting!
