### ISSUE TITLE
Release community.postgresql 3.0.0

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/community.postgresql#210]
##### SUMMARY
I suggest:
- Linking all related issues/PRs to this issue
- Releasing 3.0.0 right after Ansible `7` release (i.e. next autumn / fall) so that we'll reduce the affected audience to only people who install the collection manually. It'll be included in Ansible `8`.

**Comment by Andersson007** [comment]
https://github.com/ansible-collections/community.postgresql/issues/208

**Comment by Andersson007** [comment]
https://github.com/ansible-collections/community.postgresql/pull/209

**Comment by Andersson007** [comment]
https://github.com/ansible-collections/community.postgresql/pull/209

**Comment by Andersson007** [comment]
https://github.com/ansible-collections/community.postgresql/issues/189

**Comment by Andersson007** [comment]
@hunleyd @tcraxs any thoughts ?

**Comment by hunleyd** [comment]
wfm

any reason we don't use GH milestones?

**Comment by Andersson007** [comment]
> wfm
> 
> any reason we don't use GH milestones?

No reason, just nobody suggested:) I'll add a note to google about it to my TODO but if it's worth doing, no need to wait for my feedback, just do:)
