### ISSUE TITLE
remove priv argument to the postgresql_user module 

### ISSUE THREAD

**Issue by hunleyd** [ansible-collections/community.postgresql#212]
##### SUMMARY

Given that the `postgresql_privs` module exists for granting/revoking permissions on relations to roles, the `priv` argument of the `postgresql_user` module seems redundant.  I understand that it is probably convenient for folks, but as I see it:
- its duplicate functionality
- its duplicate code
- it muddies two different activities into one module (which seems anti-KISS)

As such, I propose deprecating and then (eventually) removing it.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
postgresql_user

**Comment by hunleyd** [comment]
opinions wanted: @andersson007 @tcraxs @DanScharon @jtelcontar @domainfun @klando @MichaelDBA @marcosdiez @felixfontein

**Comment by keithf4** [comment]
Sounds like a good idea to me. That would then turn the `db` argument into something more like the `maintenance_db` argument in the `postgresql_db` module. Could maybe rename that for consistency but leave the old `db` as an alias for it.

**Comment by Andersson007** [comment]
@hunleyd thanks for bringing this up!

**+1** from me provided that
- we are sure that `postgresql_privs` covers all related features of `postgresql_user`.
- we'll announce it now and introduce a warning when the `priv` parameter is used saying something like `the parameter is deprecated and will be removed ..., use the postgresql_privs module instead`
- we are planning to release the next major release after Ansible 7 next fall, so users of Ansible package will get the update in ~1 year.

In addition to the folks mentioned above, @kostiantyn-nemchenko @sebasmannem @keithf4 @Tas-sos @marcflausino @asifiqbal your opinions?

**Comment by acozine** [comment]
This will require some refactoring of our playbooks. However, the change does seem logical and tidy.

On balance: +1.

**Comment by Andersson007** [comment]
@hunleyd if you wanna pick it up, please go ahead (i think, the implementation should be the same to the last your similar PR)

**Comment by hunleyd** [comment]
@Andersson007 yup, planning to tackle it. we're in the middle of a release at $dayjob, so time has  been an issue

**Comment by Andersson007** [comment]
> @Andersson007 yup, planning to tackle it. we're in the middle of a release at $dayjob, so time has been an issue

@hunleyd sure, no rush with this at all as it's been as is now for many years

**Comment by bendem** [comment]
Just wanted to say, you deprecated using `priv` on `postgresql_user`, but most example still point to using `priv` with `postgresql_user`. Might want to show users the better way.

**Comment by Andersson007** [comment]
@bendem good catch, thanks! @hunleyd we forgot about the examples:)

**Comment by bendem** [comment]
Also, `priv` is documented on `postgresql_user` but not `privs` on `postgresql_privs` :)
