### ISSUE TITLE
Drop support of Ansible 2.9 and ansible-base 2.10

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/community.postgresql#243]
##### SUMMARY
Example https://github.com/ansible-collections/community.network/pull/426, partly, we need only:
- [x] ~~Remove lines from the AZP matrix (stable-2.9, stable-2.10)~~ Updated: they've been already removed
- [X] Adjust README
- [X] Update `plugins/module_utils/version.py` (as in the PR)
- [X] Create a changelog fragment with `major_changes:` notifying users that we stop support the versions but it doesn't mean any incompatibility introduction in the near future, we just stop testing against it. However we recommend to switch to ansible-core 2.11 or later.
- [X] After merging, backport it to stable-1
- [X] Release  1.* and 2.* fix or minor releases

**Comment by Andersson007** [comment]
@hunleyd would you like to pick it up? No rush with this at all.
If you have no time, please let me know.

**Comment by hunleyd** [comment]
@Andersson007 i spoke with @jchancojr and he'll do the code change under my guidance and I'll do the releases

**Comment by jchancojr** [comment]
> @Andersson007 i spoke with @jchancojr and he'll do the code change under my guidance and I'll do the releases

Confirmed. Thanks @hunleyd

**Comment by Andersson007** [comment]
@jchancojr thank you for your interest in helping with the collection! I sent an invite

**Comment by hunleyd** [comment]
backport in #247

**Comment by Andersson007** [comment]
so there's the last step - releasing the collection
if any of you wanna release, please go ahead.
if you have no time, please let me know, i'll do it.

**Comment by hunleyd** [comment]
i posted on matrix that i was planning to release them today. i was waiting to see if you approved #248 ;)
I'll get the releases out today @Andersson007

**Comment by Andersson007** [comment]
@hunleyd perfect, thanks!
