### ISSUE TITLE
PostgreSQL community pinboard

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/community.postgresql#30]
[![GitHub community.postgresql issues](https://img.shields.io/github/issues/ansible-collections/community.postgresql)](https://github.com/ansible-collections/community.postgresql/issues)[![GitHub community.postgresql PRs](https://img.shields.io/github/issues-pr/ansible-collections/community.postgresql)](https://github.com/ansible-collections/community.postgresql/pulls)

_Copied from [#435](https://github.com/ansible/community/issues/435) originally created by Dag Wieers_

We could collectively benefit from forming a [Working Group](https://github.com/ansible-collections/community.postgresql/wiki/PostgreSQL-Working-Group) related to PostgreSQL integration. We have quite some contributors on Github and users on IRC that are interested in improving this integration.

So this issue is a call for potential interested parties (earlier and existing contributors to Ansible). The benefits of having a Working Group is that members of the Working Group can:

- test, review and approve existing PostgreSQL PRs
- work collectively on the PostgreSQL roadmap
- provide a single-point-of-contact for interested PostgreSQL contributors
- collaborate on an PostgreSQL-specific Wiki

**Comment by dericcrago** [comment]
[AnsibleFest]: https://www.ansible.com/ansiblefest
[Ansible Contributor Summit]: https://ansiblecs202109.eventbrite.com/?aff=github
[Hackathon]: https://hackmd.io/@ansible-community/contrib-summit-202109#Hackathon
[Ansible Contributor Summit 2021.09 HackMD]: https://hackmd.io/@ansible-community/contrib-summit-202109

**Reminder - [AnsibleFest] and [Ansible Contributor Summit] are 1 week away!**

In case you missed it, we will also be having a **[Hackathon]** throughout the entire **[Ansible Contributor Summit]** and **[AnsibleFest]**. This is a great opportunity to collaborate in real time with other members of the Ansible Community!

For more info and the latest updates, please see the **[Ansible Contributor Summit 2021.09 HackMD]**.

**Comment by Andersson007** [comment]
[Ansible Contributor Summit]: https://ansiblecs202109.eventbrite.com/?aff=github
[Hackathon]: https://hackmd.io/@ansible-community/contrib-summit-202109#Hackathon
[Ansible Contributor Summit 2021.09 HackMD]: https://hackmd.io/@ansible-community/contrib-summit-202109

**Reminder** - Day 1 of the [Ansible Contributor Summit] and the [Hackathon] start tomorrow (Tuesday, 28 September 2021)!

For more info and the latest updates, please see the **[Ansible Contributor Summit 2021.09 HackMD]**.

**Comment by stefanvdm-em** [comment]
Hi everyone,

Thank you for all your work on this fantastic collection!

I want to take a stab at contributing to the project by adding a new module **postgresql_funcs** and saw on the [WG](https://github.com/ansible-collections/community.postgresql/wiki/PostgreSQL-Working-Group) that we should mention it here.

_PS: Contributing to open source projects is a new exercise for me... I might end up asking some silly questions._

**Comment by hunleyd** [comment]
hi @stefanvdm-em and welcome!

if you would, please open an issue describing the work you propose, and then make your PR "against" that issue. and don't worry about asking "silly" questions in that issue, we were all new at this once (some of us still are!) so we're happy to help.

**Comment by Andersson007** [comment]
@stefanvdm-em the project is totally newbie friendly, so welcome!:) We'd be happy to answer any questions.
You can be interested in reading the [guidelines](https://github.com/ansible/community-docs/).

**Comment by Andersson007** [comment]
closing in favor of forum https://github.com/ansible-collections/community.postgresql/pull/612, thanks everyone! See you on the [forum](https://forum.ansible.com/g/PostgreSQLTeam):) please join the team
