### ISSUE TITLE
Multiple queries should return multiple results

### ISSUE THREAD

**Issue by felipenazario** [ansible-collections/community.postgresql#312]
##### SUMMARY

I believe that if the script file has **N** SQL queries, it should return **N** results. But today it **only** returns the **last** SQL Query in the script file.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.postgresql.postgresql_script

##### ANSIBLE VERSION

```txt
ansible [core 2.11.9] 
  config file = /home/blue/ansible.cfg
  configured module search path = ['/home/blue/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  ansible collection location = /home/blue/collections
  executable location = /usr/bin/ansible
  python version = 3.6.15 (default, Sep 23 2021, 15:41:43) [GCC]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```txt
Collection                Version
------------------------- -------
ansible.posix             1.4.0  
bioinformatica.aplicativo 1.0.0  
community.crypto          2.4.0  
community.docker          2.7.0  
community.general         5.3.0  
community.mysql           3.3.0  
community.postgresql      2.1.5  
infrabr.aplicativo        1.0.0  
infrabr.auditoria         1.0.0  
infrabr.docker            1.0.0  
infrabr.geral             1.0.0  
infrabr.helm              1.0.0  
infrabr.k8s               1.0.0  
infrabr.repositorio       1.0.0  
infrabr.sdk               1.0.0  
infrabr.seguranca         1.0.0  
infrabr.servico           1.0.0  
infrabr.servidor          1.0.0  
kubernetes.core           2.3.2  
oracle.oci                2.54.0
```

##### CONFIGURATION

```txt
CALLBACKS_ENABLED(/home/blue/ansible.cfg) = ['ansible.posix.timer', 'ansible.posix.profile_roles', 'ansible.posix.profile_tasks', 'ansible.builtin.oneline']
COLLECTIONS_PATHS(/home/blue/ansible.cfg) = ['/home/blue/collections']
DEFAULT_FORKS(/home/blue/ansible.cfg) = 10
DEFAULT_HOST_LIST(/home/blue/ansible.cfg) = ['/home/blue/inventories/docker/hosts.ini']
DEFAULT_PRIVATE_ROLE_VARS(/home/blue/ansible.cfg) = True
DEFAULT_ROLES_PATH(/home/blue/ansible.cfg) = ['/home/blue/roles']
DEFAULT_TIMEOUT(/home/blue/ansible.cfg) = 15
DEPRECATION_WARNINGS(/home/blue/ansible.cfg) = True
HOST_KEY_CHECKING(/home/blue/ansible.cfg) = False
INTERPRETER_PYTHON(/home/blue/ansible.cfg) = auto
```

##### OS / ENVIRONMENT

uname -a

```txt
Linux localhost.localdomain 5.3.18-150300.59.76-default #1 SMP Thu Jun 16 04:23:47 UTC 2022 (2cc2ade) x86_64 x86_64 x86_64 GNU/Linux
```

cat /etc/os-release

```txt
NAME="openSUSE Leap"
VERSION="15.3"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.3"
PRETTY_NAME="openSUSE Leap 15.3"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.3"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
```

##### STEPS TO REPRODUCE

```yaml
- name: 'Create test file.'
  ansible.builtin.lineinfile:
    create: true
    path: "/tmp/test.sql"
    regexp: '^'
    line: >-
      select current_database();
      select version();

- name: "Query"
  community.postgresql.postgresql_script:
    login_db: "postgres"
    login_user: "postgres"
    login_password: "123"
    login_port: 5432
    path: "/tmp/test.sql"
  register: output

- name: "Print var."
  ansible.builtin.debug:
    msg: "{{ output }}"
```

##### EXPECTED RESULTS

```sh
ok: [postgres_origin] => {
    "msg": {
        "changed": true,
        "failed": false,
        "query": "select current_database(); select version();\n",
        "query_result": [
            {
                "current_database": "postgres"
            },
            {
                "version": "PostgreSQL 12.11 on x86_64-pc-linux-musl, compiled by gcc (Alpine 11.2.1_git20220219) 11.2.1 20220219, 64-bit"
            }
        ],
        "rowcount": 1,
        "statusmessage": "SELECT 1"
    }
}
```

##### ACTUAL RESULTS

```sh
ok: [postgres_origin] => {
    "msg": {
        "changed": true,
        "failed": false,
        "query": "select current_database(); select version();\n",
        "query_result": [
            {
                "version": "PostgreSQL 12.11 on x86_64-pc-linux-musl, compiled by gcc (Alpine 11.2.1_git20220219) 11.2.1 20220219, 64-bit"
            }
        ],
        "rowcount": 1,
        "statusmessage": "SELECT 1"
    }
```

**Comment by hunleyd** [comment]
thanks for the report @felipenazario ! i agree with your suggestion. we shall endeavor to make it happen.

**Comment by Andersson007** [comment]
@felipenazario thanks for reporting the issue

Currently the module executes a SQL script file content as a whole, at once and the postgres python driver returns the result of the last query - it just works that way `because a cursor only stores the results of the last query.`

It's is possible to implement returning multiple results via splitting a content of SQL file into separate queries and execute them one by one and appending the results to a list which will be returned then BUT:
- it was a source of bugs (and resp. pain) in `postgresql_query`, you can't just split by `;` as this character can be a part of queries, e.g. strings you insert or select.
- if we come up with another solution, like introducing another query separator (for example, a blank line or whatever) which we declare official, it will lead to `breaking changes` or to appearing a bunch of extra options and return values as it was in `postgresql_query`

So the main question is: do we really need to complicate the code and, with it, probably introduce bugs and pain for users and developers?
If yes, please suggest your solution (i'm really not against if we come up with something simple and working well, preferably w/o breaking changes).

Any thoughts? If you involve your friends in the discussion, it'd be great:)

**Comment by felipenazario** [comment]
Hi @Andersson007,

I understand your point of view, this behavior of multiple queries is a frequent task, not an exceptional task and it was already present before using **query_list** and **query_all_results**.

When I read the [postgresql_query docs](https://docs.ansible.com/ansible/latest/collections/community/postgresql/postgresql_query_module.htmll) it says:

> WARNING The path_to_script and as_single_query options as well as the query_list and query_all_results return values have been deprecated and will be removed in community.postgresql 3.0.0, please use the [community.postgresql.postgresql_script](https://docs.ansible.com/ansible/latest/collections/community/postgresql/postgresql_script_module.html#ansible-collections-community-postgresql-postgresql-script-module) module to execute statements from scripts.

Please correct if my understand is wrong, but according to this warning the **postgresql_query** is no longer able to provide multiple queries feature since 3.0.0, because it has been deprecated and if you want this feature please use **postgresql_script** module, since it is responsible to execute **statements** (note the plural) from scripts.

This warning gave me the idea that this feature was only moved between the two modules, but now looks like it was completed lost.

**Comment by Andersson007** [comment]
>This warning gave me the idea that this feature was only moved between the two modules, but now looks like it was completely lost.

@felipenazario you're right, it was completely lost because of the reasons I described [above](https://github.com/ansible-collections/community.postgresql/issues/312#issuecomment-1210337044).

**Comment by felipenazario** [comment]
Hi @Andersson007,

Once I understood the real scenario, I believe that the current behavior of **postgresql_script** makes more sense as it is. Since in general, we expect a single result from a SQL script batch process.

> Currently the module executes a SQL script file content as a whole, at once and the postgres python driver returns the result of the last query - it just works that way because a cursor only stores the results of the last query.

As I mentioned before, the behavior of multiple queries is a **frequent** task, not an **exceptional** task. Then, my **suggestion** is that attribute **query** from the module **postgresql_query** should be an **Array** instead of a **String**. In this scenario the Array would be executed one by one **in the current session** and **appending** the results to a list which will be returned.

Once each SQL statement **take one position** in the array. I believe that it **mitigates or resolves** the problem of the **query separator** that you already mentioned.

**Comment by Andersson007** [comment]
Hi @felipenazario 
>As I mentioned before, the behavior of multiple queries is a frequent task, not an exceptional task. Then, my suggestion is that attribute query from the module postgresql_query should be an Array instead of a String. In this scenario the Array would be executed one by one in the current session and appending the results to a list which will be returned.

We used exactly this approach in postgresql_query.
The question is how to split the queries from the script file safely?
We used `;` but it can be a part of text values also withing the queries, e.g. `INSERT INTO text VALUES ("my text ; blah ; blah"); SELECT 1`.
If someone can write a **safe** implementation of an algorithm that splits queries by `;` (all possible scenarios) and thoroughly covers it with unit tests and integration tests, I'd be happy to see it merged.

**Comment by felipenazario** [comment]
Hi @Andersson007,

I have been think about this multiple queries feaure and I came up with this idea of compose the all previous mentions.

```yaml
- name: "Query"
  community.postgresql.postgresql_query:
    login_db: "postgres"
    login_user: "postgres"
    login_password: "123"
    login_port: 5432
    query:
      - select current_database();
      - select version();
      - INSERT INTO text VALUES ("my text ; blah ; blah"); SELECT 1
  register: output
```

Above I wrote a simple example to illustrate it. The would be executed one by one in the current session and appending the results to a list which will be returned, but all positions are executed preserving the current behavior below.

> at once and the postgres python driver returns the result of the last query - it just works that way because a cursor only stores the results of the last query.

```json
ok: [postgres_origin] => {
    "msg": {
        "changed": true,
        "failed": false,
        "query": "select current_database(); select version();\n",
        "query_result": [
            {
                "current_database": "postgres"
            },
            {
                "version": "PostgreSQL 12.11 on x86_64-pc-linux-musl, compiled by gcc (Alpine 11.2.1_git20220219) 11.2.1 20220219, 64-bit"
            },
           {
               "SELECT 1": "Some random result"
           }
        ],
        "rowcount": 1,
        "statusmessage": "SELECT 1"
    }
}
```

As you already figure out, we do not split multiple queries in the same position. At least for now, when somebody send a Pull Request providing a special regex to find all query delimiters in all scenarios, it would be merged.

**Comment by Andersson007** [comment]
@felipenazario yes, for now, the result of INSERT in `INSERT INTO text VALUES ("my text ; blah ; blah"); SELECT 1` will be cut off by the driver

**Comment by felipenazario** [comment]
Hi @Andersson007,

Can I count on that this feature will be inserted in the team backlog?

**Comment by Andersson007** [comment]
@felipenazario hi, sorry for the late reply, tough times. yes, sure, we'll leave the issue open, thank you!
It sounds very fair, we just need to come up with implementation details and to find someone who can invest time in implementing it.
