### ISSUE TITLE
Add action_groups to runtime.yml

### ISSUE THREAD

**Issue by cmanzur** [ansible-collections/community.postgresql#313]
##### SUMMARY
Please add a array in meta/runtime.yml to be able to use **module defaults**. 
Like here: https://docs.ansible.com/ansible/latest/user_guide/playbooks_module_defaults.html

This is very useful to don't repeat  **login_host, login_user, login_password** on every **task** (postgresql_user, postgresql_db, etc...)

##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by hunleyd** [comment]
Thanks for the suggestion @cmanzur ! This sounds like a great idea to me. I'll see if we can get it coded up soon.

**Comment by wschoot** [comment]
Yes, this sounds good!

**Comment by Andersson007** [comment]
oh, missed the issue somehow.. sorry, thanks for reporting!
does anyone want to pick it up? we have the [Quick-start guide](https://docs.ansible.com/ansible/devel/community/create_pr_quick_start.html) if you have no experience
