### ISSUE TITLE
Missing options for pg_hba contype

### ISSUE THREAD

**Issue by btoussaint** [ansible-collections/community.postgresql#349]
##### SUMMARY
The postgresql_pg_hba module does currently not support all valid options for contype

##### ISSUE TYPE
The contypes "hostgssenc" and "hostnogssenc" are supported by postgresql but not this module.

##### COMPONENT NAME
postgresql_pg_hba

**Comment by Andersson007** [comment]
@btoussaint hello, thanks for the feature request!

@betanummeric @sebasmannem would you like to take a look?

**Comment by Andersson007** [comment]
> It should be quite easy to support those types. My PR is not tested yet.

@betanummeric cool, thanks for picking this up!

**Comment by betanummeric** [comment]
@Andersson007 It's ready for review now

**Comment by betanummeric** [comment]
It's merged and backported now.
