### ISSUE TITLE
Ansible pg_dump custom format dump

### ISSUE THREAD

**Issue by shiva1343** [ansible-collections/community.postgresql#388]
Please raise issues via the [new interface](https://github.com/ansible/ansible/issues/new/choose)

I would like to know if there is any module to take pg_dump custom format dump (pg_dump -Fc) using ansible..

Thanks, 
Shiva

**Comment by hunleyd** [comment]
hello @shiva1343 ! at this time there is no module in the collection for doing the same. you will need to use the `cmd` or `shell` module depending on your needs.

**Comment by Andersson007** [comment]
@shiva1343 hello, thanks for reporting the issue!

Could you please try to use the [postgresql_db](https://docs.ansible.com/ansible/latest/collections/community/postgresql/postgresql_db_module.html) module with a dump file name containing the `.pgc` suffix and say how it works?
I think it's an issue in the module's documentation.

Looking forward to your feedback

**Comment by hunleyd** [comment]
Wow, I did not realize postgresql_db could handle dump/restore. TIL. Sorry for misdirecting you @shiva1343

**Comment by Andersson007** [comment]
@shiva1343 could you please give us any feedback ^

**Comment by Andersson007** [comment]
closed via https://github.com/ansible-collections/community.postgresql/pull/398
