### ISSUE TITLE
postgresql_privs: double use of login_* arguments

### ISSUE THREAD

**Issue by felixfontein** [ansible-collections/community.postgresql#406]
##### SUMMARY
The module argumentspec declares multiple `login_*` options as aliases of other options, **while these are separate options defined in the docs fragment / module utils**!

This looks like a bug to me, and can cause warnings by ansible-core if someone uses both the "alias" and the real option (like `host` and `login_host`). If the intention was to 'default' these options to the `login_*` versions, this should be done by explicit code.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
postgresql_privs

**Comment by Andersson007** [comment]
@felixfontein thanks for reporting the issue!

Agreed, doesn't look good.

Will see what we can do with it

**Comment by Andersson007** [comment]
working on it

**Comment by Andersson007** [comment]
created a PR https://github.com/ansible-collections/community.postgresql/pull/407 please take a look
