### ISSUE TITLE
module development: postgresql_utils

### ISSUE THREAD

**Issue by aleksvagachev** [ansible-collections/community.postgresql#413]
Hello everyone. I have an idea to implement a module for using postgresql utilities for creating backups, database copies and database initialization. (pg_basebackup, pg_dumpall, initdb). I can transfer using pg_dump and pg_restore to this module, since, in my opinion, the call of all PostgreSQL DBMS utilities can be in one module. 

If it can be implemented, I am ready to try to do it.

##### SUMMARY
Creating copies of the database and initializing the database

##### ISSUE TYPE
Module development

##### COMPONENT NAME
postgresql_utils/postgresql_backup

##### ADDITIONAL INFORMATION
Example usage:
- name: Database initialization
  community.postgresql.postgresql_utils:
    state: initdb
    encoding: UTF-8
    lc_collate: en_EN.UTF-8
    target: /var/lib/pgsql/data
    target_opts: --wal-segsize=32M --waldir=/var/wal

- name: Take a base backup of a Postgres
  community.postgresql.postgresql_utils:
    login_user: test
    login_password: test
    login_host: 127.0.0.1
    port: 5432
    state: basebackup
    target: /var/lib/pgsql/data
    target_opts: --max-rate=100M

**Comment by hunleyd** [comment]
Any reason to not create postgresql_initdb and postgresql_basebackup modules? Then each one is obviously named for what it does and can specify the options for that command (or at least the common options)

**Comment by betanummeric** [comment]
Hi @aleksvagachev, are you proposing simple wrappers around the postgres executables or do you want logic built on top of that? Can you provide a feature wishlist?
I think this collection is too generic to offer more than syntactic sugar around the postgres features.
Is it worth to create and maintain modules for initdb, pg_dumpall, ... when those tasks could be done with `ansible.builtin.command`?

**Comment by keithf4** [comment]
I kind of agree with betanummeric. Unless this is adding something onto these commands other than being a wrapper, seems to just be extra modules to maintain that do the exact same thing.

**Comment by Andersson007** [comment]
I'm also not sure if we need just wrappers.
I myself created some wrappers here in the past (like `postgresql_copy`, for example).
I wish they did NOT exist...
Unfortunately there were no wise folks around 4+ years ago who suggested not doing it.
I'm OK if they provide features like idempotency but i don't see how such module(s) could do it.

**Comment by aleksvagachev** [comment]
@betanummeric @keithf4 @Andersson007 @hunleyd I wanted to add simple wrappers around postgres executables, maybe add data compression.
Having thought over your words, apparently there really is no need for this module. Thank you for your comments.

**Comment by Andersson007** [comment]
@aleksvagachev yeah, the collective wisdom is a thing!
In some cases, wrappers can be fine if they provide good things like, in case of this collection, using features of the driver or convenient return value representation like `postgresql_query` module but in general we should avoid **only** wrappers.

So can we close the issue?
