### ISSUE TITLE
Duplicates in Notes for postgresql_ext

### ISSUE THREAD

**Issue by elpavel** [ansible-collections/community.postgresql#476]
##### SUMMARY

There are several duplicates in the Notes section of postgresql_ext module documentation.
Some of the notes in postgresql_ext.py duplicate the default notes from doc_fragments.
https://docs.ansible.com/ansible/latest/collections/community/postgresql/postgresql_ext_module.html#notes

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
plugins/modules/postgresql_ext.py

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.4]
config file = /home/pavel/.ansible.cfg
configured module search path = ['/home/pavel/Projects/Modules']
ansible python module location = /home/pavel/.local/lib/python3.10/site-packages/ansible
ansible collection location = /home/pavel/.ansible/collections:/usr/share/ansible/collections
executable location = /home/pavel/.local/bin/ansible
python version = 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] (/usr/bin/python3)
jinja version = 3.0.3
libyaml = True
```

**Comment by Andersson007** [comment]
@elpavel hello, thanks for raising the issue! Would you like to submit a pull request?
The docs live under the plugins/modules/postgresql_ext.py in the DOCUMENTATION section.
You can use the Edit button or this [guide](https://docs.ansible.com/ansible/devel/community/create_pr_quick_start.html).
Please let us know

**Comment by elpavel** [comment]
Please check the pull request. It removes the duplicates from postgresql_ext, and also adds some highlights to the generic notes (affecting the look of almost all the modules).
Cheers
