### ISSUE TITLE
feature request: support more obj_type in postgresql_owner

### ISSUE THREAD

**Issue by betanummeric** [ansible-collections/community.postgresql#482]
Currently, the _postgresql_owner_ module supports altering the owner of these kinds of things:

- `database`
- `function`
- `matview`
- `sequence`
- `schema`
- `table`
- `tablespace`
- `view`

But there are `ALTER $kind $thing OWNER TO $owner` commands (checked for postgres 15) for more unusual kinds of things:

- `aggregate`
- `collation`
- `conversion`
- `domain`
- `event trigger`
- `foreign data wrapper`
- `foreign table`
- `function`
- `language`
- `large object`
- `operator`
- `operator class`
- `operator family`
- `procedure`
- `publication`
- `routine`
- `server`
- `statistics`
- `subscription`
- `tablespace`
- `text search configuration`
- `text search dictionary`
- `type`

It would be nice to have them integrated in the _postgresql_owner_ module (available as `obj_type`).
I'm mostly interested in this subset of the currently-not-supported object kinds:

- `aggregate`
- `collation`
- `conversion`
- `domain`
- `function`
- `operator`
- `operator class`
- `operator family`
- `procedure`
- `routine`
- `type`

**Comment by Andersson007** [comment]
Sounds like a great idea to extend the functionality with those types (the subset imo would be enough and then adding the rest on demand)

**Comment by RealGreenDragon** [comment]
I'm working on this issue

**Comment by RealGreenDragon** [comment]
Partially fixed by PR #555
