### ISSUE TITLE
zero-length delimited error granting group to role using postgresql_privs module

### ISSUE THREAD

**Issue by csamarajeewa** [ansible-collections/community.postgresql#49]
##### SUMMARY

Receiving the following error when granting group access to a role using community.general.postgresql_privs module. I did not have any problems using postgresql_privs module with ansible 2.8 and 2.9 for the same purpose and same args.

"msg": "zero-length delimited identifier at or near \"\"\"\"\nLINE 1: GRANT \"\"REDACTED-ROLE\"\" TO \"REDACTED-USER\";\n              ^\n"

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.general.postgresql_privs

##### ANSIBLE VERSION

```paste below
ansible 2.10.4
  config file = None
  configured module search path = ['/REDACT/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /REDACT/ansible-venv/ansible10/lib/python3.8/site-packages/ansible
  executable location = /REDACT/ansible-venv/ansible10/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
```

##### CONFIGURATION

```paste below

"module_args": {
    "ca_cert": null,
    "database": "REDACTED",
    "fail_on_role": true,
    "grant_option": false,
    "host": "REDACTED",
    "login": "REDACTED",
    "login_host": "REDACTED",
    "login_password": "REDACTED",
    "login_unix_socket": "",
    "login_user": "REDACTED",
    "objs": "REDACTED",
    "password": "REDACTED",
    "port": REDACTED,
    "privs": null,
    "roles": "REDACTED",
    "schema": null,
    "session_role": null,
    "ssl_mode": "require",
    "state": "present",
    "target_roles": null,
    "trust_input": true,
    "type": "group",
    "unix_socket": ""
}

```
Note the user name has "_" character in it.

##### OS / ENVIRONMENT

Ubuntu Focal

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by felixfontein** [comment]
@csamarajeewa the postgres modules have moved to the https://github.com/ansible-collections/community.postgresql/ repository (they are no longer included in community.general 2.0.0). I've transferred your issue to the correct repository.

**Comment by Andersson007** [comment]
@csamarajeewa thanks for reporting the issue!
CC @Dorn- @andytom @ilicmilan @kostiantyn-nemchenko @matburt @nerzhul @sebasmannem @tcraxs

**Comment by Andersson007** [comment]
@csamarajeewa could you try this module with 2.10.5
passing `commynity.postgresql.postgresql_privs:` instead of `postgresql_privs:` or `community.general.postgresql_privs:`?

**Comment by csamarajeewa** [comment]
Thanks I have no issues when using community.postgresql.postgresql_privs .

**Comment by Andersson007** [comment]
@csamarajeewa thanks for the feedback! the bugfix probably was not backported to `community.general`, I'll check when time allows
