### ISSUE TITLE
Add Psycopg 3 support

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/community.postgresql#499]
##### SUMMARY
- Related PR https://github.com/ansible-collections/community.postgresql/pull/220 that can be used when implementing actual support (the obstacle was fixed on the driver's stuff)
- Another big related issue to solve it adding testing against psycopg 3, i.e. to have testing against 2 and 3

**Comment by elpavel** [comment]
It looks like the Linux distributions don't include psycopg 3 yet (except debian/bookworm). While the distros are catching up and psycopg 3 becoming available, it may be enough to have just one test target with both versions of psycopg available. The existing modules will still work, and can be slowly updated one by one. Assuming the updated modules will try to import version 3 first. Broader testing of psycopg 3 can be added later when packages become widely available.
So an easy way to enable testing against psycopg 3 could be
- add a new target (let say ubuntu2204)
- keep psycopg2 for this target
- add psycopg 3 on this target via Pip

**Comment by Andersson007** [comment]
@elpavel yep, new target with ubuntu2204 sounds like a great idea and we could specify in the `setup_postgresql_db` target a variable to install `psycopg3` when there's `ubuntu2204` (though i didn't test this).

When i took the first try in https://github.com/ansible-collections/community.postgresql/pull/220, i stumbled upon one incompatibility in `psycopg3` which would require a lot of code re-writing.
I discussed that with their devs and their added a toggle (a variable afaik) which allows to say the driver to keep the compatibility on the initialization stage. So it should be quite easy to add the support now (see my PR).

Would you like to pick it up? Anyway, thanks for your participation!

**Comment by Andersson007** [comment]
@elpavel IIRC yes,
Thanks a lot!

**Comment by elpavel** [comment]
@Andersson007 @hunleyd should we consider supporting all (old) releases of psycopg2 ?

2.5 was released in 2013
2.8 was released in 2019

The two above releases added functionality which is also present in Psycopg 3, and using that functionality would simplify the code as the same would work for Psycopg 2 and 3.

Examples:
[psycopg2.Error.diag](https://www.psycopg.org/docs/module.html#psycopg2.Error.diag) added in 2.5
[psycopg2.errors](https://www.psycopg.org/docs/errors.html#module-psycopg2.errors) added in 2.8

**Comment by hunleyd** [comment]
> @Andersson007 @hunleyd should we consider supporting all (old) releases of psycopg2 ?
> 
> 2.5 was released in 2013 2.8 was released in 2019
> 
> The two above releases added functionality which is also present in Psycopg 3, and using that functionality would simplify the code as the same would work for Psycopg 2 and 3.
> 
> Examples: [psycopg2.Error.diag](https://www.psycopg.org/docs/module.html#psycopg2.Error.diag) added in 2.5 [psycopg2.errors](https://www.psycopg.org/docs/errors.html#module-psycopg2.errors) added in 2.8

i don't have a problem raising the minimum version to 2.8 to make the code more similar between psycopg v2 and v3

**Comment by Andersson007** [comment]
> @Andersson007 @hunleyd should we consider supporting all (old) releases of psycopg2 ?
> 
> 2.5 was released in 2013 2.8 was released in 2019
> 
> The two above releases added functionality which is also present in Psycopg 3, and using that functionality would simplify the code as the same would work for Psycopg 2 and 3.
> 
> Examples: [psycopg2.Error.diag](https://www.psycopg.org/docs/module.html#psycopg2.Error.diag) added in 2.5 [psycopg2.errors](https://www.psycopg.org/docs/errors.html#module-psycopg2.errors) added in 2.8

I'm OK with 2.8+ too.
In this case, imo, we should (in a separate PR):
- Add a changelog fragment with a `major_chage:` entry saying `- postgres modules - the minimum version of psycopg2 library the collection supports is 2.9 (https://this pr url)`
- Add this info to README
- Change `plugins/doc_fragments/postgresql.py` requirements key `[ 'psycopg2 >= 2.8' ]`
- Maybe add a warning to the code if the version is lower show something like "you use psycopg2 VER which is not supported by the collection, consider upgrading it to at least 2.8"".

Ideas? Maybe some of the item would be excessive

**Comment by elpavel** [comment]
Thanks for the feedback. All those points are sensible, making the minimum supported version visible.

**Comment by Andersson007** [comment]
RHEL 8: yeah, it's more than relevant, so would be good to support 2.7.5.
RHEL/CentOS 7: not sure, if it doesn't cost us a lot in terms of support/time/effort, I'd vote with +0.

**Comment by elpavel** [comment]
> RHEL 8: yeah, it's more than relevant, so would be good to support 2.7.5. RHEL/CentOS 7: not sure, if it doesn't cost us a lot in terms of support/time/effort, I'd vote with +0.

For me the 'important' versions are 2.5 and 2.8, each introducing important functionality. So 2.5 is good, if we stay below 2.8.
