### ISSUE TITLE
Can we remove some modules?

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/community.postgresql#508]
##### SUMMARY
I suggest evaluating whether we can remove some modules from the collection. Some of the modules were created before other modules that can perform same things like `postgresql_query` for example.

Two necessary conditions (suggest yours) for a module to be deprecated and removed one day:
1. Things can be done by another module w/o dramatic decrease of conveniency.
2. Things don't work well (e.g. a module is not idempotent or partly idempotent) 

#### Suggested order (feel free to suggest changes):
1. Discussion
2. Vote
3. Deprecation (with a note that users can raise their concerns / justifications why we shouldn't remove it)
4. Removal in one of the next major releases. The version number will be determined based on the deprecation release date (when users will start getting warnings + at least a year or so)

#### Candidates:

- [postgresql_idx](https://github.com/ansible-collections/community.postgresql/blob/main/plugins/modules/postgresql_idx.py): not idempotent, checks only name. Can we use `postgresql_query`, ideas?

- [postgresql_sequence](https://github.com/ansible-collections/community.postgresql/blob/main/plugins/modules/postgresql_sequence.py): same as the above

- [postgresql_table](https://github.com/ansible-collections/community.postgresql/blob/main/plugins/modules/postgresql_table.py): same as above

- [postgresql_slot](https://github.com/ansible-collections/community.postgresql/blob/main/plugins/modules/postgresql_slot.py): same as above

- [postgresql_schema](https://github.com/ansible-collections/community.postgresql/blob/main/plugins/modules/postgresql_schema.py): same as above

- [postgresql_copy](https://github.com/ansible-collections/community.postgresql/blob/main/plugins/modules/postgresql_copy.py): does it bring any value or can be replaced with `shell/command` or `postgresql_query` ?

- [postgresql_user_obj_stat_info](https://github.com/ansible-collections/community.postgresql/blob/main/plugins/modules/postgresql_user_obj_stat_info.py): not sure if useful. If someone needs it, maybe they can use `postgresql_query`? ideas?

- your suggestion

Some of them were introduced by me before `postgresql_query` module. This is `antipattern` i used due to lack of experience. We should prevent of getting similar stuff into the collection..

Ideas? Please before approving removal, inspect corresponding code

**Comment by Andersson007** [comment]
@hunleyd @jchancojr @betanummeric @aleksvagachev @RealGreenDragon @keithf4 @l00ptr  @laurent-indermuehle and other interested folks, ideas?

**Comment by betanummeric** [comment]
We should keep `postgresql_copy`. Of course you could do anything with a shell/command, but `postgresql_copy` makes the specific task significantly easier to write and read. `postgresql_query` is not a substitute, because it does not support stdin or stdout redirection, which is the major feature of `postgresql_copy`.
I'm not a user of `postgresql_copy`, but I would use it to automate reading and writing big amounts of data (`COPY` is way more efficient than `INSERT`).

**Comment by pgguru** [comment]
Kinda hard to get the cats back in the bag once they're out, but maybe something along the lines of an extended deprecation period with pointers to the appropriate workaround in both docs and code; say a year or so, _then_ remove them.

**Comment by keithf4** [comment]
I'm in the same boat as Doug. I know I've personally made use of `_schema` and `_table` quite a bit when trying to ensure monitoring objects exist inside the database with the necessary permissions. Doing all that via `_query` would be extremely tedious and much more error prone. The modules at least provide a consistent template for doing very common operations. 

I do agree that in the future, we can evaluate the usefulness of a new module and where else it might fit better, but I think at least these that you've mentioned so far should stay.

The only one I could see adjusting would possibly be combining the `_table` and `_index` one somehow? Indexes can only exist on a table, so maybe it could be some sort of sub-dictionary list? Even then, not sure that would be less confusing or more useful in the long run. There's still a lot of options to index creation that the module helps to simplify. If its lack of idempotency  is the main issue, maybe just see about fixing that? I have some code in this python script from pg_partman that actually looks at the definition of the index to determine if a parent index already exists on the child before creating it - https://github.com/pgpartman/pg_partman/blob/master/bin/common/reapply_indexes.py#L60

**Comment by RealGreenDragon** [comment]
Totally agree, all modules more specific than `_query` are always useful for code clarity and a minimum of idempotence.

**Comment by aleksvagachev** [comment]
It would be a good idea if these modules were not used. I like the **postgresql_slot** module, I would not like to remove it.

1) Maybe try moving part of the **postgresql_user_obj_stat_info** module to postgresql_info? Then you can get rid of it.
2) The **postgresql_sequence** module, can be considered for removal. For sequence management, in my opinion, you need to pay more attention than just trusting the module.

**Comment by RealGreenDragon** [comment]
> It would be a good idea if these modules were not used. I like the **postgresql_slot** module, I would not like to remove it.
> 
>     1. Maybe try moving part of the **postgresql_user_obj_stat_info** module to postgresql_info? Then you can get rid of it.
> 
>     2. The **postgresql_sequence** module, can be considered for removal. For sequence management, in my opinion, you need to pay more attention than just trusting the module.

Right, both good ideas for me (better keep only one info module, and in effect also I never used sequence module).

**Comment by Andersson007** [comment]
Thanks for the great feedback team! Let's collect it for a while.
If people are happy to use them, they shouldn't be removed but rather maybe improved one day if needed.
I thought nobody needs it but was wrong:)

We should take a closer look at @aleksvagachev 's suggestion.

Speaking about `postgresql_copy`, there's the `copy()` method in the driver. Maybe it brings some benefits compared to using just SQL. We should scrutinize this.

I think this discussion will be a source for at least a couple of good issues (which everyone is welcome to open at any moment)

**Comment by elpavel** [comment]
`postgresql_lang` would a good candidate for removal.

The [documentation](https://www.postgresql.org/docs/12/sql-createlanguage.html) says
_As of PostgreSQL 9.1, most procedural languages have been made into “extensions”, and should therefore be installed with CREATE EXTENSION not CREATE LANGUAGE._

Also I suspect the `postgresql_lang` package has issues on newer Postgres versions, as DROP LANGUAGE on its own won't work.

**Comment by RealGreenDragon** [comment]
> `postgresql_lang` would a good candidate for removal.
> 
> The [documentation](https://www.postgresql.org/docs/12/sql-createlanguage.html) says _As of PostgreSQL 9.1, most procedural languages have been made into “extensions”, and should therefore be installed with CREATE EXTENSION not CREATE LANGUAGE._
> 
> Also I suspect the `postgresql_lang` package has issues on newer Postgres versions, as DROP LANGUAGE on its own won't work.

With my PR #545 I removed almost all `postgresql_ext` module limitations (idempotence, check_mode, return values, documentation, etc.) so `postgresql_ext` can be a good replace for `postgresql_lang`.

**Comment by Andersson007** [comment]
fyi folks, @elpavel has started postgresql_lang deprecation in https://github.com/ansible-collections/community.postgresql/pull/559
