### ISSUE TITLE
README: update list of PG versions we test against

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/community.postgresql#509]
##### SUMMARY
The [testing section](https://github.com/ansible-collections/community.postgresql#tested-with-ansible-core) of README does not reflect the real state of things. It should be updated

1. [Run integration tests locally](https://docs.ansible.com/ansible/devel/community/create_pr_quick_start.html) or inspect test logs in any recent open PRs to find PG version we test against on `centos7`, `fedora37`, `ubuntu2004`.

2. Raise a PR to reflect your finding in the README's [test section](https://github.com/ansible-collections/community.postgresql#tested-with-ansible-core).

**Comment by elpavel** [comment]
Hi @Andersson007 I will review the tested versions.

**Comment by Andersson007** [comment]
@elpavel thanks a lot! Also would you like to update our CI matrix https://github.com/ansible-collections/news-for-maintainers/issues/49 
If yes, please don't put Fixes .. in the PR as we shouldn't close the issue:)
