### ISSUE TITLE
path_to_script and as_single_query params are not supported anymore

### ISSUE THREAD

**Issue by dberardo-com** [ansible-collections/community.postgresql#586]
what should be the alternative ?

where is the v3+ doc?

**Comment by betanummeric** [comment]
@dberardo-com You are reffering to the `postgresql_query` module, right?

The [`postgresql_script` module](https://docs.ansible.com/ansible/latest/collections/community/postgresql/postgresql_script_module.html) should proivde replacing features.

I'm not sure why docs.ansible.com is not showing the docs for the latest version. As a fallback, you can read the docs in a less-prettier form [in the code](https://github.com/ansible-collections/community.postgresql/blob/main/plugins/modules/postgresql_script.py#L11).

**Comment by Andersson007** [comment]
@dberardo-com hi, thanks for the question!
@betanummeric thanks for answering!
Closing the issue
