### ISSUE TITLE
Galaxy: check and fix galaxy collection links

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/community.postgresql#591]
##### SUMMARY
In order to implement https://github.com/ansible-collections/news-for-maintainers/issues/59, we should check and fix all Galaxy collection urls if they present in the repo

**Comment by thatonepolishkid** [comment]
Hello there! Just inquiring if this issues is still ongoing.

**Comment by Andersson007** [comment]
@thatonepolishkid hello, welcome to the project! It was fixed, thanks! Closing. Please check out our README for forum and Matrix channel links.
