### ISSUE TITLE
Set role or database parameters

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/community.postgresql#598]
### Discussed in https://github.com/ansible-collections/community.postgresql/discussions/576

<div type='discussions-op-text'>

<sup>Originally posted by **ivanov17** September  5, 2023</sup>
Hello! What is the best way to set role or database parameters?

There is the `community.postgresql.postgresql_set` module that uses ALTER SYSTEM to set PostgreSQL server configuration parameters.

Unfortunately, I don't see anything like this for altering role or database parameters.

Is using SQL queries with `community.postgresql.postgresql_query` currently the only option for this? Or maybe there are some other options that I didn't notice?

Are there plans to implement other `*_set` modules such as `postgresql_user_set` and `postgresql_db_set`?</div>

**Comment by Andersson007** [comment]
See the discussion [comment](https://github.com/ansible-collections/community.postgresql/discussions/576#discussioncomment-6989634) to get examples of what the reporter wants to achieve

**Comment by optica-phoffmann** [comment]
@Andersson007 Looks like links (discussion and comment) do not work anymore.

**Comment by Andersson007** [comment]
@optica-phoffmann hi, thanks for pinging! here it is. Also there's a [quick-start dev guide](https://docs.ansible.com/ansible/devel/community/create_pr_quick_start.html) which can help

![Screenshot from 2024-04-24 10-43-46](https://github.com/ansible-collections/community.postgresql/assets/34477873/d11a3e5f-adf5-467c-af31-a112492a872f)
