### ISSUE TITLE
Publication creation doesn't support specifying columns for published table

### ISSUE THREAD

**Issue by kacperk** [ansible-collections/community.postgresql#609]
##### SUMMARY

Publication creation doesn't support specifying columns for which publication should be created - 
example SQL - `CREATE PUBLICATION users_filtered FOR TABLE users (user_id, firstname)` 

Right now if I pass as a table name  `users (user_id, firstname)` it will quote the whole thing, which ends up as invalid SQL
 
##### ISSUE TYPE
- Missing functionality

##### COMPONENT NAME

community.postgresql.postgresql_publication

##### ADDITIONAL INFORMATION

It should allow to set-up publication with a limited column set - since it is possible in Postgres >= 15

Specs could look like this:
```yaml
tables:
  - "public"."users" (user_id, firstname)
```
or
```yaml
tables:
  - users:
    - user_id
    - firstname
```

**Comment by Andersson007** [comment]
@kacperk hello, thanks for reporting the issue!
I'll put the `help_wanted` label + a link to our [quick-start guide](https://docs.ansible.com/ansible/devel/community/create_pr_quick_start.html) if anyone is interested to pick it.
