### ISSUE TITLE
Documentation improvement for fast ramp up

### ISSUE THREAD

**Issue by silvio** [ansible-collections/community.postgresql#64]
##### SUMMARY
I need help using your module. Maybe the documentation can be improved in this area.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
all

##### ANSIBLE VERSION

```
ansible 2.10.6
  config file = /development/projects/Firmware.Tools.AnsiblePlaybooks/ansible.cfg
  configured module search path = ['/home/sfr/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.2 (default, Feb 20 2021, 18:40:11) [GCC 10.2.0]
```

I'm trying to use `community.postgresql` and failing miserably!
What did I do: First install via: `ansible-galaxy collection install community.postgresql`. Then in the playbook just reference via

```
collections:
  - community.postgresql
```

The log output tells me that the collection is loaded, but the desired role is not found.
```
Loading collection community.postgresql from /home/sfr/.ansible/collections/ansible_collections/community/postgresql
ERROR! the role 'community.postgresql.postgresql_db' was not found in /development/projects/Firmware.Tools.AnsiblePlaybooks/roles:/home/sfr/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/development/projects/Firmware.Tools.AnsiblePlaybooks
```

What am I doing wrong?

**Comment by Andersson007** [comment]
@silvio hi, thanks for reporting this!
One question before going further - if you remove the `collections: - community.postgresql` directive and use `community.postgresql.postgresql_db:` instead of just `postgresql_db:` in the module's invocations, does it work?

**Comment by silvio** [comment]
Hi @Andersson007 ,
Sorry, I have to take back my help-request.

I have tried to load the roles via `include_role`, and this isn't possible. When I use `postgresql_db` or `community.postgresql.postgresql_db` as a task it is functional.

**Comment by Andersson007** [comment]
@silvio ah, ok, no problem:)
