### ISSUE TITLE
Postgresql_query and Postgresql_* modules do not provide option for target_session_attrs

### ISSUE THREAD

**Issue by zmehu** [ansible-collections/community.postgresql#69]
##### SUMMARY
Postgresql_* modules use Python psycopg2 library and this library allow use when connection to cluster attribute target_session_attrs. When we set target_session_attrs="read-write" we will connect to master/write host. It's useful when we use PostgreSQL clusters.

##### ISSUE TYPE
- Provide attribute target_session_attrs and passthrough to psycopg2

##### COMPONENT NAME
postgresql_query, postgresql_user, postgresql_db

##### ADDITIONAL INFORMATION
This postgres modules are based on psycopg2 python module and this module support target_session_attrs and cluster connection. Current ansible modules require extension for supporting this attribute on connection part.

```python
conn = psycopg2.connect(host="ip1,ip2",
            port=port,
            database=db,
            user=user,
            password=pass,
            sslmode='require',
            target_session_attrs="read-write")
```

**Comment by Andersson007** [comment]
@zmehu , hi, thanks for the feature idea, sounds very interesting though I'm not an expert. Do you like to implement this yourself?
We should be careful about the driver versions - that all of them support it.

@tcraxs @andytom @Dorn- @popov83 @sebasmannem @kostiantyn-nemchenko what do you think?

**Comment by Andersson007** [comment]
@SzymonMGR hello, thanks for reminding! If you'd like to add these options, please go ahead (but let us know before),
otherwise I'll ping folks directly. What do you think?

**Comment by SzymonMGR** [comment]
Hi ! Maybe it's possible to try with gitlab team firstly ?

**Comment by Andersson007** [comment]
> Hi ! Maybe it's possible to try with gitlab team firstly ?

I don't understand, could you elaborate a bit more?

**Comment by SzymonMGR** [comment]
Sure - with pinging folks directly. "... otherwise I'll ping folks directly." ;)

**Comment by Andersson007** [comment]
implemented in https://github.com/ansible-collections/community.postgresql/pull/329,

Thanks everyone!
