### ISSUE TITLE
Windows supported ?

### ISSUE THREAD

**Issue by markatdxb** [ansible-collections/community.postgresql#699]
##### SUMMARY
Hello, i guess silly question to ask . Are the modules supported in Windows environment ?

**Comment by Andersson007** [comment]
@markatdxb hello, thanks for asking the question.
They cannot be run directly on windows but you can:
1. Make postgres on your windows server listen to outside connections
2. run playbook on your ansible controller using the `delegate_to: localhost` directive in the postgres tasks and all of those remote login options of the modules like `login_host: <your windows server ip postgres is listening at>`, `login_port: ...`, `login_user: ..`, `login_password: ..`, etc.

Is it helpful?

**Comment by markatdxb** [comment]
Its definitely helpful !!! Dunno why i didnt think about doing it this way. Thanks a lot

**Comment by Andersson007** [comment]
@markatdxb sure, you're welcome! and there are no questions considered silly in this project
