### ISSUE TITLE
publication creation does not support all tables in specific schemas

### ISSUE THREAD

**Issue by commodis** [ansible-collections/community.postgresql#709]
##### SUMMARY

The current `publication`-module does not support the creation of a publication with all tables in specific schemas.

```sql
CREATE PUBLICATION sales_publication FOR TABLES IN SCHEMA marketing, sales;
```

--- 

https://www.postgresql.org/docs/current/sql-createpublication.html

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

`community.postgresql.postgresql_publication`

##### ADDITIONAL INFORMATION

Current link to the documentation https://docs.ansible.com/ansible/latest/collections/community/postgresql/postgresql_publication_module.html

**Comment by Andersson007** [comment]
@commodis hello, thanks for reporting the issue! I'll put the `help_wanted` label on it hoping someone has time soon to take a look
For newcomers, there's a [quick start dev guide](https://docs.ansible.com/ansible/devel/community/create_pr_quick_start.html) that can help. If anyone's gonna take a look, please put explicitly in a comment

**Comment by Andersson007** [comment]
the pr https://github.com/ansible-collections/community.postgresql/pull/718 is ready for review
