### ISSUE TITLE
Command "ansible-galaxy collection list" is not give the expected output 

### ISSUE THREAD

**Issue by mukesh-tanuku** [ansible-collections/community.postgresql#712]
##### SUMMARY

I want to verify the collections installed on the control node by using this command _ansible-galaxy collection list_ but it is giving me the below output
```
usage: ansible-galaxy collection [-h] COLLECTION_ACTION ...
ansible-galaxy collection: error: argument COLLECTION_ACTION: invalid choice: 'list' (choose from 'init', 'build', 'publish', 'install')
```

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

ansible-galaxy collection list
##### ANSIBLE VERSION

```
ansible 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Jan  5 2024, 08:58:17) [GCC 8.5.0 20210514 (Red Hat 8.5.0-20)]


```

**Comment by Andersson007** [comment]
@mukesh-tanuku hello, any questions/issues about ansible-galaxy should be raised in another repo https://github.com/ansible/ansible.
Also you use a very old Ansible version (~4-5 y.o), so i would start with upgrading it

**Comment by Andersson007** [comment]
Closing the issue as it's out of scope of the project, anyway thanks!
