### ISSUE TITLE
CI: change Ubuntu2204 target to test against PG 16 and Ubuntu2404 against PG 17, update README

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/community.postgresql#743]
##### SUMMARY
CI: change Ubuntu2204 target to test against PG 16 and Ubuntu2404 against PG 17, update README

Be prepared to fix [maybe a lot of] errors related to PG 17 in our modules code and tests and handle them backwards-compatibly

See https://github.com/ansible-collections/community.postgresql/pull/740

**Comment by cameronmurdoch** [comment]
Sure - I am still working on #732 but can take a look at this once that is fixed. At work we will want to deploy pg17 fairly soon so this would be something helpful for me too :-)

**Comment by Andersson007** [comment]
@cameronmurdoch great, i'll remove the help wanted label and assign this to you then. If anything changes, please let us know, thanks!

**Comment by Andersson007** [comment]
@cameronmurdoch if you haven't started yet, I could take a look at least at some modules tests compatibility with PG 17

**Comment by cameronmurdoch** [comment]
Sure, go ahead. #732 is nearly ready for review, but I have had a sick child to look after which has slowed down finishing.

**Comment by Andersson007** [comment]
Sure, no worries and no rush, I wish your kid will get well soon!
