### ISSUE TITLE
postgresql_set adding extra quotes for comma seperated list

### ISSUE THREAD

**Issue by jkman340** [ansible-collections/community.postgresql#84]
##### SUMMARY
Using postgresql_set module to set a value for a setting  ( For example 'shared_preload_libraries') that contains comma separated list.  The module is wrapping extra quotes around the resulting value in postgresql.auto.conf file causing the postgresql service to fail.

For example:
```
- postgresql_set:
     name: shared_preload_libraries
     value: somelib,someotherlib
```
Results in this line in postgresql.auto.conf config. Because of the inner "", it treats this as a single module name and service fails to start.
`shared_preload_libraries = '"somelib,someotherlib"'`
The expected value is
`shared_preload_libraries = 'somelib,someotherlib'`

However, a single value does work
```
- postgresql_set:
     name: shared_preload_libraries
     value: somelib
```
correctly results in
`shared_preload_libraries = 'somelib'`

If I have tried various ways of formatting the string without success. 

Additionally, it would be very helpful if a list object could be passed to value instead of a string (Currently does not work).
```
- postgresql_set:
     name: shared_preload_libraries
     value:
        - somelib
        - someotherlib
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.postgresql.postgresql_set

##### ANSIBLE VERSION

```
  ansible 2.10.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]

```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
```

##### OS / ENVIRONMENT
Ubuntu 18.04 LTS

**Comment by Andersson007** [comment]
@jkman340 thanks for the issue!
I think it relates to a PostgreSQL bug. See investigation made https://github.com/ansible-collections/community.postgresql/issues/78#issuecomment-812350722

**Comment by Andersson007** [comment]
if you run `ALTER SYSTEM SET shared_preload_libraries = 'firstlib,secondlib';` via `psql`, you will get the same wrong result in `postgresql.auto.conf`, won't you?

**Comment by Andersson007** [comment]
@jkman340 I'll close the issue. If you check as I suggested above and find any inconsistencies, please let us know and we'll reopen it. Thank you!
